# General Settings
title: "D/Vision Lab"
email: "info@dvisionlab.com"
email_2: "info@dvisionlab.com"
description: >- # this means to ignore newlines until "baseurl:"
  We are a technology start-up specialized in data visualization that
  operates in the scientific, medical, engineering and services domains.

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: "VIA PASUBIO, 5 24044 DALMINE (BG) - IT C/O POINT </br> POLO PER L'INNOVAZIONE TECNOLOGICA </br> INCUBATORE D'IMPRESA DI BG"
phone_number: ""
copyright_text: "© 2022 D/Vision Lab. Some rights reserved."
vat: "VAT 04412060164"
capsoc: "SHARE CAPITAL 11.750 EUR"

google_analytics:
  enable: true
  key: "UA-157591485-1"

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11156.91484344262!2d9.5973041!3d45.6462286!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd76bda49e656b6ff!2sD%2FVision%20Lab%20s.r.l.!5e0!3m2!1sen!2sit!4v1645461727288!5m2!1sen!2sit" style="width:100%; height: 100%; border:0" allowfullscreen="" loading="lazy"></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "http://www.linkedin.com/company/dvisionlab"
      icon: "jam jam-linkedin"

    - url: "http://www.github.com/dvisionlab"
      icon: "jam jam-github"

    - url: "http://www.twitter.com/dvisionlab"
      icon: "jam jam-twitter"

    - url: "https://www.incubatore.bergamo.it/sito/settore-manifatturiero/436-d-vision-lab.html"
      icon: "jam jam-ghost-org"

