# General Settings
title: "DICOM Vision"
email: "info@dicom.vision"
email_2: "info@dicom.vision"
description: >- # this means to ignore newlines until "baseurl:"
  DICOM Vision is an innovative zero-footprint viewer designed for the storage 
  and display of medical images in the DICOM format.

# black_logo_1x: "/assets/images/logo.png"
# black_logo_2x: "/assets/images/logo@2x.png"
# light_logo_1x: "/assets/images/logo-light.png"
# light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: "VIA PASUBIO, 5 24044 DALMINE (BG) - IT C/O POINT </br> POLO PER L'INNOVAZIONE TECNOLOGICA </br> INCUBATORE D'IMPRESA DI BG"
phone_number: ""
copyright_text: "© 2023 DICOM Vision. Some rights reserved."
vat: "VAT 04485020160"
capsoc: "SHARE CAPITAL 10.000 EUR"

google_analytics:
  enable: false
  key: ""

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11156.91484344262!2d9.5973041!3d45.6462286!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47814dcac484cf73%3A0xfb6dc99b76a4185f!2sDicom%20Vision%20srl!5e0!3m2!1sen!2sit!4v1697224524231!5m2!1sen!2sit" style="width:100%; height: 100%; border:0" allowfullscreen="" loading="lazy"></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "https://www.linkedin.com/company/74176613"
      icon: "jam jam-linkedin"

    - url: "https://www.incubatore.bergamo.it/sito/settore-manifatturiero/dicom-vision.html"
      icon: "jam jam-ghost-org"

    - url: "http://www.github.com/Dicom-Vision"
      icon: "jam jam-github"
